version: '3.6'

services:
  db:
    image: "postgres:11"
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=morphus
      - POSTGRES_PASSWORD=morphus
      - POSTGRES_DB=morphus
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432

  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db

volumes:
  postgres_data:
